application: cf-ddns
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|txt))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|txt))

- url: /up/.*
  script: up.py

- url: /setdnsrecord/.*
  script: setdnsrecord.py

- url: /getdnsrecords/.*
  script: getdnsrecords.py

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: index.html
  upload: index.html
