application: cf-ddns
version: 0-9-rc
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|txt))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|txt))

- url: /css
  static_dir: /css

- url: /js
  static_dir: /js

- url: /up/.*
  script: up.py

- url: /ipup/.*
  script: ipup.py

- url: /setdnsrecord/.*
  script: setdnsrecord.py

- url: /getdnsrecords/.*
  script: getdnsrecords.py

- url: /
  static_files: index.html
  upload: index.html

- url: /.*
  static_files: index.html
  upload: index.html
